### ISSUE TITLE
Hires programs as generated with zx88dk don't work when loaded from the PICO

### ISSUE THREAD

**Issue by Sasounet** [timex-sinclair-projects/TS-Pico#3]
Hires programs as generated with zx88dk don't work when loaded from the PICO. Same programs works fine when loaded from tape or other means (it works when loaded from my Interface1Bis)

Included are two .tap files of the same program. (A simple test program that draw on screen). 

testgr1.tap 
This version don't use the hi resolution and works on the PICO. It consist of two files, a BASIC loader and machine code

testgr1TS.tap
Same program but is supposed to display the result in HiRes (512x192). It consist of 4 files (two BASIC loaders and two machine code). Its stops after the first two files are loaded. Presumably the first loader + code is to setup the computer for HiRes.

Both file were compiled with z88dk, the second with the option for HiRes on the TS-2068 i.e. with the -lgfx2068hr option.

François

[testgr.zip](https://github.com/timex-sinclair-projects/TS-Pico/files/13832183/testgr.zip)

**Comment by Sasounet** [comment]
Additional information:

The HiRes program do work with PICO installed if loaded from tape (with SAVE "tpi:tape"). So it is not the presence of the PICO that is the problem, but the loading process of that .tap file.

**Comment by factus10** [comment]
@Sasounet @guspane has updated the TS-Pico ROM and both of your files load correctly :)

Here's a short demo video of your two programs: https://www.youtube.com/watch?v=DV97h0NdOxE

Are you able to burn your own Flash ROM?

**Comment by Sasounet** [comment]
Very cool! Many thanks to Gustavio and the team. This open a wide range of HiRES apps to be produced for the TS-2068 as it is so easy to program them with Z88dk.

No I don’t have a flash ROM burner. But I can pay for the upgrade FLASH + shipping.

Eventually, I need to procure a burner. My needs are more EPROM than flash ROM, but maybe there are some burner that can do both?

**Comment by factus10** [comment]
We still have some testing to do but it's looking good. 

Ricardo has explored an in-system upgrade, since the 2068 can write to the flash, but it's not complete. We're going to discuss this at our weekly meeting on Weds and figure out the best approach. I'll touch base with you after :)

I use a "MiniPro" aka TL866; it can do eprom, flash and a bunch of microcontrollers. It's been discontinued, replaced by the T48, which can do even more. But hold off for now (don't get it just for this).
